[tool.poetry]
name = "job-research"
version = "0.0.1"
description = ""
authors = ["Pooya Haratian"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.11,<3.12"
flask = "^3.0.0"
requests = "^2.31.0"
python-dotenv = "^1.0.0"
litellm = "^1.7.7"
pyautogen = "^0.2.0"
docker = "^6.1.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
run_proxy = "job_research.runpod:app.run(debug=True)"
